### ISSUE TITLE
Connection timeouts when creating topic but not when listing topics

### ISSUE THREAD

**Issue by patelvp** [karafka/rdkafka-ruby#377] opened 2023-12-22 16:19 UTC
Setup:
- Start a server on 29092 port

Steps to reproduce:
```ruby
client_config = {
    :"bootstrap.servers" => "localhost:29092"
}
# Create the client
client = Rdkafka::Config.new(**client_config)

# ensure connectivity
# You should see all your topics
client.admin.metadata.topics.pluck(:topic_name)

# This gives out an timeout error
client.admin.create_topic('test1',1,1).wait

Error: -> Rdkafka::AbstractHandle::WaitTimeoutError: Waiting for create topic timed out after 60 seconds
```

**Comment by mensfeld** [comment] 2024-01-17 12:15
@patelvp I was not able to reproduce it. It looks like it is your setup problem. I was both able to create and list topics binded on 29092 with your example code. It is most likely that your configuration for Kafka is not fully correct. I will close it but feel free to open if you can create a reproducible repository with the code + docker setup.

**Closed by mensfeld** 2024-01-17 12:15 UTC
Labels: bug, admin
