### ISSUE TITLE
Create topic wait hanging

### ISSUE THREAD

**Issue by Kwisatx** [karafka/rdkafka-ruby#344] opened 2023-11-17 08:26 UTC
We are using rdkafka-ruby in a rails project to produce messages and create topics: ruby '3.2.2' rdkafka (0.13.0) rails (6.1.7.4)

This is the code we use for the admin side of things:

```
    def kafka_admin
      Rdkafka::Config.new(kafka_conf).admin
    end

      def create_topic
        begin
          handle = kafka_admin.create_topic(
            "#{topic}", # topic
            1,              # partition count
            3               # replication factor
          )
          handle.wait
        rescue Rdkafka::RdkafkaError => e
          # topic already exists
        end
      end
```

When I call this code on our low-traffic dev environment, or in the rails console on our higher-traffic environment, `create_topic` returns pretty much instantly, but via an API call on the higher-traffic environment `handle.wait` hangs indefinitely (at least 60 seconds, after which the request times out) even though the topic is created pretty much instantly in Kafka with the expected configuration.

I can't figure out what the issue is, we have no issue with the delivery_handles in the producers, and both messages produced and topics created are few and far between, so it shouldn't be a load issue with Kafka. The hanging also appears immediately on a fresh instance.

One strange thing I see is that in the rails logs (as well as in the console) after calling create_topic there is a `ThreadError` that appears a bit later (always one error for one call to create_topic):
```
/home/api/vendor/gems/ruby/3.2.0/gems/activesupport-6.1.7.4/lib/active_support/cache/file_store.rb:171: warning: Exception in finalizer #<Proc:0x00007fd7d062c398 /home/apiv3/vendor/gems/ruby/3.2.0/gems/rdkafka-0.13.0/lib/rdkafka/native_kafka.rb:78 (lambda)>
/home/api/vendor/gems/ruby/3.2.0/gems/rdkafka-0.13.0/lib/rdkafka/native_kafka.rb:66:in `synchronize': can't be called from trap context (ThreadError)
    from /home/api/vendor/gems/ruby/3.2.0/gems/rdkafka-0.13.0/lib/rdkafka/native_kafka.rb:66:in `synchronize'
    from /home/api/vendor/gems/ruby/3.2.0/gems/rdkafka-0.13.0/lib/rdkafka/native_kafka.rb:88:in `close'
    from /home/api/vendor/gems/ruby/3.2.0/gems/rdkafka-0.13.0/lib/rdkafka/native_kafka.rb:78:in `block in finalizer'
    from /home/api/vendor/gems/ruby/3.2.0/gems/activesupport-6.1.7.4/lib/active_support/cache/file_store.rb:171:in `directory?'
...

```

Is there something we are doing wrong?

**Comment by mensfeld** [comment] 2023-11-17 08:42
This a well known issue. At the moment it is compensated by a different waiting mechanism in karafka admin: https://github.com/karafka/karafka/blob/master/lib/karafka/admin.rb#L106

I do have plans to fix it / backport it to rdkafka but it will not happen before Q1.

**Comment by mensfeld** [comment] 2023-11-17 08:53
If you consider it critical, you have three things you can do that I am aware of:
1. use karafka admin for that
2. fix it
3. consider supporting my kafka efforts so I can fix things like that faster

**Comment by Kwisatx** [comment] 2023-11-17 08:57
OK, thanks for the quick answer.

**Comment by mensfeld** [comment] 2023-11-21 09:06
duplicate of: https://github.com/karafka/rdkafka-ruby/issues/266

**Closed by mensfeld** 2023-11-21 09:06 UTC
Labels: bug
